#!/usr/bin/env bash
set -euo pipefail

# Stage 2b: render preview.mp4 from the staged hf-project/ produced by
# run-stage2-compose.sh.
#
# Usage: tools/scripts/run-stage2-preview.sh <slug> [--quality=low|full]
#
# Note: composition.html is the canonical, pristine composition artifact.
# hf-project/index.html is derived/disposable — re-generated by every
# run-stage2-compose.sh invocation — so we mutate dimensions there only.
# A subsequent --quality=full thus requires re-running run-stage2-compose.sh
# to restore the full data-width/data-height from composition.html.

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "Usage: $0 <slug> [--quality=low|full]"
  exit 1
fi

SLUG="$1"
QUALITY="low"
if [ "$#" -eq 2 ]; then
  case "$2" in
    --quality=low)  QUALITY="low" ;;
    --quality=full) QUALITY="full" ;;
    *) echo "ERROR: unknown arg '$2' (expected --quality=low|full)"; exit 1 ;;
  esac
fi

REPO_ROOT="$(pwd)"
EPISODE="$REPO_ROOT/episodes/$SLUG"
COMPOSITE_DIR="$EPISODE/stage-2-composite"
HF_PROJ="$COMPOSITE_DIR/hf-project"
HF_INDEX="$HF_PROJ/index.html"

[ -f "$HF_INDEX" ] || { echo "ERROR: $HF_INDEX missing — run run-stage2-compose.sh first"; exit 1; }

if [ "$QUALITY" = "low" ]; then
  # Idempotently overwrite root <div> dimensions to 720x1280. Use a temp
  # file + mv to avoid sed -i quirks on Windows Git Bash.
  TMP_INDEX="$HF_INDEX.tmp"
  sed -E -e 's#data-width="[0-9]+"#data-width="720"#' \
         -e 's#data-height="[0-9]+"#data-height="1280"#' \
         "$HF_INDEX" > "$TMP_INDEX"
  # Sanity: ensure patched file still has a root <div> with both attrs.
  grep -Eq 'data-width="720"' "$TMP_INDEX" && grep -Eq 'data-height="1280"' "$TMP_INDEX" \
    || { echo "ERROR: dimension patch failed (no data-width/height match)"; rm -f "$TMP_INDEX"; exit 1; }
  mv "$TMP_INDEX" "$HF_INDEX"
  HF_FPS=30
  # hyperframes 0.4.31 quality choices are draft|standard|high (no "medium").
  # "standard" is the moderate option for the low-res preview.
  HF_Q=standard
else
  HF_FPS=60
  HF_Q=high
fi

HF_OUT="$COMPOSITE_DIR/preview.mp4"
rm -f "$HF_OUT"
npx -y hyperframes render "$HF_PROJ" \
  -o preview.mp4 \
  -f "$HF_FPS" \
  -q "$HF_Q" \
  --format mp4 || { echo "ERROR: hyperframes render failed"; exit 1; }

# `-o` may be interpreted relative to the project dir or to cwd, or HF may
# place it in the default renders/<name>_<ts>.mp4 location. Relocate to $HF_OUT.
if [ ! -f "$HF_OUT" ]; then
  if [ -f "$HF_PROJ/preview.mp4" ]; then
    mv "$HF_PROJ/preview.mp4" "$HF_OUT"
  elif [ -f "$REPO_ROOT/preview.mp4" ]; then
    mv "$REPO_ROOT/preview.mp4" "$HF_OUT"
  elif ls "$HF_PROJ"/renders/*.mp4 >/dev/null 2>&1; then
    mv "$(ls -t "$HF_PROJ"/renders/*.mp4 | head -n1)" "$HF_OUT"
  fi
fi

[ -f "$HF_OUT" ] || { echo "ERROR: preview.mp4 not produced"; exit 1; }
echo "Preview ready: $HF_OUT (quality=$QUALITY). Awaiting CP3 review."
